/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Classes.Comprador;
import Classes.Control;
import Classes.Factura;
import Classes.Producto;
import Classes.Tienda;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Urbano
 */
public class CrearFactura extends javax.swing.JFrame {

    ArrayList<Producto> listaProductos = new ArrayList<>();
    Run padre;

    /**
     * Creates new form CrearFactura
     *
     * @param runPadre
     */
    public CrearFactura(Run runPadre) {
        initComponents();
        this.padre = runPadre;
    }

    public void actualizarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) this.tablaArticulos.getModel();
            modelo.setRowCount(0);
            for (int i = 0; i < listaProductos.size(); i++) {
                modelo = (DefaultTableModel) this.tablaArticulos.getModel();
                modelo.setRowCount(i + 1);
                this.tablaArticulos.setValueAt(this.listaProductos.get(i).getCodigo(), i, 0);
                this.tablaArticulos.setValueAt(this.listaProductos.get(i).getNombre(), i, 1);
                this.tablaArticulos.setValueAt(this.listaProductos.get(i).getPrecioConIVA(), i, 2);
            }
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error escribiendo datos en tabla", JOptionPane.ERROR_MESSAGE);
            //Añadir evento error escribir tabla mientras se creaba factura
        }
    }

    public boolean hayArticulosEnTabla() {
        if (this.tablaArticulos.getRowCount() >= 1 && !this.listaProductos.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "No hay artículos para insertar en la factura", "Error al crear factura", JOptionPane.ERROR_MESSAGE);
            //Añadir evento de error al crear factura por no haber artículos
            return false;
        }
    }

    public boolean datosFacturaCorrectos() {
        boolean r = true;
        if (this.numeroPedidoTxt.getText().equals("Número de pedido")) {
            r = false;
        }
        if (this.diaFechaTxt.getText().equals("Día")) {
            r = false;
        }
        if (this.mesFechaTxt.getText().equals("Mes")) {
            r = false;
        }
        if (this.añoFechaTxt.getText().equals("Año")) {
            r = false;
        }
        if (this.formaPagoComboBox.getSelectedIndex() == 0) {
            r = false;
        }
        if (this.gastosEnvioTxt.getText().equals("€")) {
            r = false;
        }
        if (!r) {
            JOptionPane.showMessageDialog(this, "Por favor, rellene adecuadamente los datos de facturación", "Error al crear factura", JOptionPane.ERROR_MESSAGE);
        }
        return r;
    }

    public boolean datosTiendaCorrectos() {
        boolean r = true;
        if (this.nombreTiendaTxt.getText().equals("Nombre de la tienda")) {
            r = false;
        }
        if (this.webTIendaTxt.getText().equals("Página web")) {
            r = false;
        }
        if (this.direccionTiendaTxt.getText().equals("Dirección")) {
            r = false;
        }
        if (!r) {
            JOptionPane.showMessageDialog(this, "Por favor, rellene adecuadamente los datos de la tienda", "Error al crear factura", JOptionPane.ERROR_MESSAGE);
        }
        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreArticuloTxt = new javax.swing.JTextField();
        tipoArticuloTxt = new javax.swing.JTextField();
        codigoArticuloTxt = new javax.swing.JTextField();
        precioArticuloTxt = new javax.swing.JTextField();
        precioArticuloIncluyeIvaRadioButon = new javax.swing.JRadioButton();
        insertarArticuloButon = new javax.swing.JButton();
        limpiarArticuloButon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        compradorExistenteComboBox = new javax.swing.JComboBox<>();
        nombreCompradorTxt = new javax.swing.JTextField();
        apellidosCompradorTxt = new javax.swing.JTextField();
        dniCompradorTxt = new javax.swing.JTextField();
        emailCompradorTxt = new javax.swing.JTextField();
        direccionCompradorTxt = new javax.swing.JTextField();
        telefonoCompradorTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        numeroPedidoTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        diaFechaTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mesFechaTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        añoFechaTxt = new javax.swing.JTextField();
        otraFormaPagoTxt = new javax.swing.JTextField();
        formaPagoComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gastosEnvioTxt = new javax.swing.JTextField();
        gastosEnvioConIvaRadioButon = new javax.swing.JRadioButton();
        descuentoConIvaRadioButon = new javax.swing.JRadioButton();
        descuentoTxt = new javax.swing.JTextField();
        contieneDescuentoRadioButon = new javax.swing.JRadioButton();
        limpiarFacturaButon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        seleccionarTiendaComboBox = new javax.swing.JComboBox<>();
        nombreTiendaTxt = new javax.swing.JTextField();
        webTIendaTxt = new javax.swing.JTextField();
        direccionTiendaTxt = new javax.swing.JTextField();
        limpiarTiendaButon = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        resetButon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos generales de factura");

        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaArticulos);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nombre");

        jLabel3.setText("Tipo");

        jLabel4.setText("Código");

        jLabel5.setText("Precio");

        nombreArticuloTxt.setText("Nombre del artículo");
        nombreArticuloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreArticuloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreArticuloTxtFocusLost(evt);
            }
        });
        nombreArticuloTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nombreArticuloTxtMouseReleased(evt);
            }
        });
        nombreArticuloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArticuloTxtActionPerformed(evt);
            }
        });

        tipoArticuloTxt.setText("Categoría");
        tipoArticuloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tipoArticuloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoArticuloTxtFocusLost(evt);
            }
        });

        codigoArticuloTxt.setText("Identificador del artículo");
        codigoArticuloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoArticuloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoArticuloTxtFocusLost(evt);
            }
        });

        precioArticuloTxt.setText("€");
        precioArticuloTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioArticuloTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioArticuloTxtFocusLost(evt);
            }
        });

        precioArticuloIncluyeIvaRadioButon.setText("Precio incluye IVA");
        precioArticuloIncluyeIvaRadioButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioArticuloIncluyeIvaRadioButonActionPerformed(evt);
            }
        });

        insertarArticuloButon.setText("Insertar a factura");
        insertarArticuloButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarArticuloButonActionPerformed(evt);
            }
        });

        limpiarArticuloButon.setText("Limpiar");
        limpiarArticuloButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarArticuloButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreArticuloTxt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tipoArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoArticuloTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precioArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precioArticuloIncluyeIvaRadioButon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(limpiarArticuloButon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertarArticuloButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(codigoArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(precioArticuloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioArticuloIncluyeIvaRadioButon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertarArticuloButon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarArticuloButon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Artículos");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Datos propios de producto");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Datos del comprador:");

        compradorExistenteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar existente" }));

        nombreCompradorTxt.setText("Nombre");
        nombreCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreCompradorTxtFocusLost(evt);
            }
        });
        nombreCompradorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCompradorTxtActionPerformed(evt);
            }
        });

        apellidosCompradorTxt.setText("Apellidos");
        apellidosCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidosCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidosCompradorTxtFocusLost(evt);
            }
        });
        apellidosCompradorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosCompradorTxtActionPerformed(evt);
            }
        });

        dniCompradorTxt.setText("DNI");
        dniCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dniCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dniCompradorTxtFocusLost(evt);
            }
        });
        dniCompradorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniCompradorTxtActionPerformed(evt);
            }
        });

        emailCompradorTxt.setText("Email");
        emailCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailCompradorTxtFocusLost(evt);
            }
        });
        emailCompradorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCompradorTxtActionPerformed(evt);
            }
        });

        direccionCompradorTxt.setText("Dirección");
        direccionCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionCompradorTxtFocusLost(evt);
            }
        });
        direccionCompradorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionCompradorTxtActionPerformed(evt);
            }
        });

        telefonoCompradorTxt.setText("Teléfono");
        telefonoCompradorTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoCompradorTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoCompradorTxtFocusLost(evt);
            }
        });

        jButton3.setText("Limpiar comprador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionCompradorTxt)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compradorExistenteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailCompradorTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCompradorTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(apellidosCompradorTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dniCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telefonoCompradorTxt)))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(compradorExistenteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionCompradorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Pedido");

        numeroPedidoTxt.setText("Número de pedido");
        numeroPedidoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroPedidoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroPedidoTxtFocusLost(evt);
            }
        });

        jLabel10.setText("Fecha");

        diaFechaTxt.setText("Día");
        diaFechaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diaFechaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaFechaTxtFocusLost(evt);
            }
        });
        diaFechaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFechaTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("/");

        mesFechaTxt.setText("Mes");
        mesFechaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mesFechaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesFechaTxtFocusLost(evt);
            }
        });

        jLabel12.setText("/");

        añoFechaTxt.setText("Año");
        añoFechaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                añoFechaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                añoFechaTxtFocusLost(evt);
            }
        });

        otraFormaPagoTxt.setText("Especificar medio de pago");
        otraFormaPagoTxt.setEnabled(false);
        otraFormaPagoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otraFormaPagoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                otraFormaPagoTxtFocusLost(evt);
            }
        });

        formaPagoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar forma de pago", "Tarjeta", "Transferencia", "Transferencia SOFORT", "Paypal", "V.me by VISA", "Metalico", "Contra reembolso", "Financiacion", "Otro..." }));
        formaPagoComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                formaPagoComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        formaPagoComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formaPagoComboBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formaPagoComboBoxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formaPagoComboBoxMouseReleased(evt);
            }
        });

        jLabel13.setText("Forma de pago");

        jLabel14.setText("Gastos de envío");

        gastosEnvioTxt.setText("€");
        gastosEnvioTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gastosEnvioTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gastosEnvioTxtFocusLost(evt);
            }
        });

        gastosEnvioConIvaRadioButon.setText("Gastos de envío incluye IVA");

        descuentoConIvaRadioButon.setText("Descuento incluye IVA");
        descuentoConIvaRadioButon.setEnabled(false);

        descuentoTxt.setText("€");
        descuentoTxt.setEnabled(false);
        descuentoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descuentoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descuentoTxtFocusLost(evt);
            }
        });

        contieneDescuentoRadioButon.setText("Contiene descuento");
        contieneDescuentoRadioButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contieneDescuentoRadioButonMouseReleased(evt);
            }
        });
        contieneDescuentoRadioButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contieneDescuentoRadioButonActionPerformed(evt);
            }
        });

        limpiarFacturaButon.setText("Limpiar factura");
        limpiarFacturaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarFacturaButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(limpiarFacturaButon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(contieneDescuentoRadioButon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(descuentoTxt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(formaPagoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(gastosEnvioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(gastosEnvioConIvaRadioButon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(otraFormaPagoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descuentoConIvaRadioButon)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroPedidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addComponent(diaFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(añoFechaTxt)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(numeroPedidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(diaFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(mesFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(añoFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(formaPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otraFormaPagoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(gastosEnvioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gastosEnvioConIvaRadioButon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contieneDescuentoRadioButon)
                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descuentoConIvaRadioButon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarFacturaButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Datos de la tienda:");

        seleccionarTiendaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar existente" }));

        nombreTiendaTxt.setText("Nombre de la tienda");
        nombreTiendaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTiendaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTiendaTxtFocusLost(evt);
            }
        });

        webTIendaTxt.setText("Página web");
        webTIendaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                webTIendaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                webTIendaTxtFocusLost(evt);
            }
        });

        direccionTiendaTxt.setText("Dirección");
        direccionTiendaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTiendaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTiendaTxtFocusLost(evt);
            }
        });

        limpiarTiendaButon.setText("Limpiar tienda");
        limpiarTiendaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTiendaButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTiendaTxt)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seleccionarTiendaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(webTIendaTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccionTiendaTxt)
                    .addComponent(limpiarTiendaButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(seleccionarTiendaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTiendaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webTIendaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTiendaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarTiendaButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setText("Aceptar y guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        resetButon.setBackground(new java.awt.Color(204, 0, 0));
        resetButon.setText("Resetear todo");
        resetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton2.setText("Examinar");

        jTextField1.setEditable(false);
        jTextField1.setText("Directorio de factura");

        jLabel16.setText("Seleccione el archivo original de su factura para guardar una copia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addGap(13, 13, 13)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(974, 715));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void precioArticuloIncluyeIvaRadioButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioArticuloIncluyeIvaRadioButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioArticuloIncluyeIvaRadioButonActionPerformed

    private void diaFechaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFechaTxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_diaFechaTxtActionPerformed

    private void nombreArticuloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArticuloTxtActionPerformed
        // TODO add your handling code here:
        if (this.nombreArticuloTxt.getText().equals("Nombre del artículo")) {
            this.nombreArticuloTxt.setText("");
        }
    }//GEN-LAST:event_nombreArticuloTxtActionPerformed

    private void insertarArticuloButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarArticuloButonActionPerformed
        // TODO add your handling code here:
        boolean todoCorrecto = true;
        if (this.nombreArticuloTxt.getText().toUpperCase().equals("NOMBRE DEL ARTÍCULO") || this.nombreArticuloTxt.getText().isEmpty()) {
            todoCorrecto = false;
        }
        if (this.tipoArticuloTxt.getText().toUpperCase().equals("CATEGORÍA") || this.tipoArticuloTxt.getText().isEmpty()) {
            todoCorrecto = false;
        }
        if (this.codigoArticuloTxt.getText().toUpperCase().equals("IDENTIFICADOR DEL ARTÍCULO") || this.codigoArticuloTxt.getText().isEmpty()) {
            todoCorrecto = false;
        }
        if (this.precioArticuloTxt.getText().toUpperCase().equals("€") || this.precioArticuloTxt.getText().isEmpty()) {
            todoCorrecto = false;
        }
        if (todoCorrecto) {
            try {
                Producto p = new Producto(this.nombreArticuloTxt.getText().toUpperCase(), this.tipoArticuloTxt.getText().toUpperCase(), Integer.parseInt(this.codigoArticuloTxt.getText()), Double.parseDouble(this.precioArticuloTxt.getText()), this.precioArticuloIncluyeIvaRadioButon.isSelected());
                this.listaProductos.add(p);
                this.actualizarTabla();
                this.limpiarArticuloButonActionPerformed(evt);
            } catch (Exception error) {
                JOptionPane.showMessageDialog(this, error.getMessage(), "Error al guardar artículo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos correctamente", "No se puede añadir el artículo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_insertarArticuloButonActionPerformed

    private void limpiarArticuloButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarArticuloButonActionPerformed
        // TODO add your handling code here:
        this.nombreArticuloTxt.setText("Nombre del artículo");
        this.tipoArticuloTxt.setText("Categoría");
        this.codigoArticuloTxt.setText("Identificador del artículo");
        this.precioArticuloTxt.setText("€");
        this.precioArticuloIncluyeIvaRadioButon.setSelected(false);
    }//GEN-LAST:event_limpiarArticuloButonActionPerformed

    private void contieneDescuentoRadioButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contieneDescuentoRadioButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contieneDescuentoRadioButonActionPerformed

    private void nombreArticuloTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreArticuloTxtMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreArticuloTxtMouseReleased

    private void nombreArticuloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreArticuloTxtFocusLost
        // TODO add your handling code here:
        if (this.nombreArticuloTxt.getText().isEmpty()) {
            this.nombreArticuloTxt.setText("Nombre del artículo");
        }
    }//GEN-LAST:event_nombreArticuloTxtFocusLost

    private void nombreArticuloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreArticuloTxtFocusGained
        // TODO add your handling code here:
        if (this.nombreArticuloTxt.getText().equals("Nombre del artículo")) {
            this.nombreArticuloTxt.setText("");
        }
    }//GEN-LAST:event_nombreArticuloTxtFocusGained

    private void tipoArticuloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoArticuloTxtFocusGained
        // TODO add your handling code here:
        if (this.tipoArticuloTxt.getText().equals("Categoría")) {
            this.tipoArticuloTxt.setText(null);
        }
    }//GEN-LAST:event_tipoArticuloTxtFocusGained

    private void tipoArticuloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoArticuloTxtFocusLost
        // TODO add your handling code here:
        if (this.tipoArticuloTxt.getText().isEmpty()) {
            this.tipoArticuloTxt.setText("Categoría");
        }
    }//GEN-LAST:event_tipoArticuloTxtFocusLost

    private void codigoArticuloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoArticuloTxtFocusGained
        // TODO add your handling code here:
        if (this.codigoArticuloTxt.getText().equals("Identificador del artículo")) {
            this.codigoArticuloTxt.setText(null);
        }
    }//GEN-LAST:event_codigoArticuloTxtFocusGained

    private void codigoArticuloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoArticuloTxtFocusLost
        // TODO add your handling code here:
        if (this.codigoArticuloTxt.getText().isEmpty()) {
            this.codigoArticuloTxt.setText("Identificador del artículo");
        }
    }//GEN-LAST:event_codigoArticuloTxtFocusLost

    private void precioArticuloTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioArticuloTxtFocusGained
        // TODO add your handling code here:
        if (this.precioArticuloTxt.getText().equals("€")) {
            this.precioArticuloTxt.setText(null);
        }
    }//GEN-LAST:event_precioArticuloTxtFocusGained

    private void precioArticuloTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioArticuloTxtFocusLost
        // TODO add your handling code here:
        if (this.precioArticuloTxt.getText().isEmpty()) {
            this.precioArticuloTxt.setText("€");
        }
    }//GEN-LAST:event_precioArticuloTxtFocusLost

    private void numeroPedidoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroPedidoTxtFocusGained
        // TODO add your handling code here:
        if (this.numeroPedidoTxt.getText().equals("Número de pedido")) {
            this.numeroPedidoTxt.setText(null);
        }
    }//GEN-LAST:event_numeroPedidoTxtFocusGained

    private void numeroPedidoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroPedidoTxtFocusLost
        // TODO add your handling code here:
        if (this.numeroPedidoTxt.getText().isEmpty()) {
            this.numeroPedidoTxt.setText("Número de pedido");
        }
    }//GEN-LAST:event_numeroPedidoTxtFocusLost

    private void diaFechaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaFechaTxtFocusGained
        // TODO add your handling code here:
        if (this.diaFechaTxt.getText().equals("Día")) {
            this.diaFechaTxt.setText(null);
        }
    }//GEN-LAST:event_diaFechaTxtFocusGained

    private void diaFechaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaFechaTxtFocusLost
        // TODO add your handling code here:
        if (this.diaFechaTxt.getText().isEmpty()) {
            this.diaFechaTxt.setText("Día");
        }
    }//GEN-LAST:event_diaFechaTxtFocusLost

    private void mesFechaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesFechaTxtFocusGained
        // TODO add your handling code here:
        if (this.mesFechaTxt.getText().equals("Mes")) {
            this.mesFechaTxt.setText(null);
        }
    }//GEN-LAST:event_mesFechaTxtFocusGained

    private void mesFechaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesFechaTxtFocusLost
        // TODO add your handling code here:
        if (this.mesFechaTxt.getText().isEmpty()) {
            this.mesFechaTxt.setText("Mes");
        }
    }//GEN-LAST:event_mesFechaTxtFocusLost

    private void añoFechaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_añoFechaTxtFocusGained
        // TODO add your handling code here:
        if (this.añoFechaTxt.getText().equals("Año")) {
            this.añoFechaTxt.setText(null);
        }
    }//GEN-LAST:event_añoFechaTxtFocusGained

    private void añoFechaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_añoFechaTxtFocusLost
        // TODO add your handling code here:
        if (this.añoFechaTxt.getText().isEmpty()) {
            this.añoFechaTxt.setText("Año");
        }
    }//GEN-LAST:event_añoFechaTxtFocusLost

    private void formaPagoComboBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formaPagoComboBoxMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_formaPagoComboBoxMouseReleased

    private void formaPagoComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formaPagoComboBoxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formaPagoComboBoxMouseClicked

    private void formaPagoComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formaPagoComboBoxMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formaPagoComboBoxMousePressed

    private void formaPagoComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_formaPagoComboBoxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.formaPagoComboBox.getSelectedItem().equals("Otro...")) {
            this.otraFormaPagoTxt.setEnabled(true);
        } else {
            this.otraFormaPagoTxt.setEnabled(false);
        }
    }//GEN-LAST:event_formaPagoComboBoxPopupMenuWillBecomeInvisible

    private void otraFormaPagoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otraFormaPagoTxtFocusGained
        // TODO add your handling code here:
        if (this.otraFormaPagoTxt.getText().equals("Especificar medio de pago")) {
            this.otraFormaPagoTxt.setText(null);
        }
    }//GEN-LAST:event_otraFormaPagoTxtFocusGained

    private void otraFormaPagoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otraFormaPagoTxtFocusLost
        // TODO add your handling code here:
        if (this.otraFormaPagoTxt.getText().isEmpty()) {
            this.otraFormaPagoTxt.setText("Especificar medio de pago");
        }
    }//GEN-LAST:event_otraFormaPagoTxtFocusLost

    private void gastosEnvioTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gastosEnvioTxtFocusGained
        // TODO add your handling code here:
        if (this.gastosEnvioTxt.getText().equals("€")) {
            this.gastosEnvioTxt.setText(null);
        }
    }//GEN-LAST:event_gastosEnvioTxtFocusGained

    private void gastosEnvioTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gastosEnvioTxtFocusLost
        // TODO add your handling code here:
        if (this.gastosEnvioTxt.getText().isEmpty()) {
            this.gastosEnvioTxt.setText("€");
        }
    }//GEN-LAST:event_gastosEnvioTxtFocusLost

    private void contieneDescuentoRadioButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contieneDescuentoRadioButonMouseReleased
        // TODO add your handling code here:
        if (this.contieneDescuentoRadioButon.isSelected()) {
            this.descuentoTxt.setEnabled(true);
            this.descuentoConIvaRadioButon.setEnabled(true);
        } else {
            this.descuentoTxt.setEnabled(false);
            this.descuentoConIvaRadioButon.setEnabled(false);
        }
    }//GEN-LAST:event_contieneDescuentoRadioButonMouseReleased

    private void descuentoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descuentoTxtFocusGained
        // TODO add your handling code here:
        if (this.descuentoTxt.getText().equals("€")) {
            this.descuentoTxt.setText(null);
        }
    }//GEN-LAST:event_descuentoTxtFocusGained

    private void descuentoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descuentoTxtFocusLost
        // TODO add your handling code here:
        if (this.descuentoTxt.getText().isEmpty()) {
            this.descuentoTxt.setText("€");
        }
    }//GEN-LAST:event_descuentoTxtFocusLost

    private void nombreCompradorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCompradorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCompradorTxtActionPerformed

    private void apellidosCompradorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosCompradorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosCompradorTxtActionPerformed

    private void dniCompradorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniCompradorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniCompradorTxtActionPerformed

    private void emailCompradorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCompradorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCompradorTxtActionPerformed

    private void direccionCompradorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionCompradorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionCompradorTxtActionPerformed

    private void nombreTiendaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTiendaTxtFocusGained
        // TODO add your handling code here:
        if (this.nombreTiendaTxt.getText().equals("Nombre de la tienda")) {
            this.nombreTiendaTxt.setText(null);
        }
    }//GEN-LAST:event_nombreTiendaTxtFocusGained

    private void nombreTiendaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTiendaTxtFocusLost
        // TODO add your handling code here:
        if (this.nombreTiendaTxt.getText().isEmpty()) {
            this.nombreTiendaTxt.setText("Nombre de la tienda");
        }
    }//GEN-LAST:event_nombreTiendaTxtFocusLost

    private void webTIendaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_webTIendaTxtFocusGained
        // TODO add your handling code here:
        if (this.webTIendaTxt.getText().equals("Página web")) {
            this.webTIendaTxt.setText(null);
        }
    }//GEN-LAST:event_webTIendaTxtFocusGained

    private void webTIendaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_webTIendaTxtFocusLost
        // TODO add your handling code here:
        if (this.webTIendaTxt.getText().isEmpty()) {
            this.webTIendaTxt.setText("Página web");
        }
    }//GEN-LAST:event_webTIendaTxtFocusLost

    private void direccionTiendaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTiendaTxtFocusGained
        // TODO add your handling code here:
        if (this.direccionTiendaTxt.getText().equals("Dirección")) {
            this.direccionTiendaTxt.setText(null);
        }
    }//GEN-LAST:event_direccionTiendaTxtFocusGained

    private void direccionTiendaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTiendaTxtFocusLost
        // TODO add your handling code here:
        if (this.direccionTiendaTxt.getText().isEmpty()) {
            this.direccionTiendaTxt.setText("Dirección");
        }
    }//GEN-LAST:event_direccionTiendaTxtFocusLost

    private void limpiarFacturaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarFacturaButonActionPerformed
        // TODO add your handling code here:
        this.numeroPedidoTxt.setText("Número de pedido");
        this.diaFechaTxt.setText("Día");
        this.mesFechaTxt.setText("Mes");
        this.añoFechaTxt.setText("Año");
        this.formaPagoComboBox.setSelectedIndex(0);
        this.otraFormaPagoTxt.setText("Especificar medio de pago");
        this.otraFormaPagoTxt.setEnabled(false);
        this.gastosEnvioTxt.setText("€");
        this.gastosEnvioConIvaRadioButon.setSelected(false);
        this.contieneDescuentoRadioButon.setSelected(false);
        this.descuentoTxt.setText("€");
        this.descuentoTxt.setEnabled(false);
        this.descuentoConIvaRadioButon.setSelected(false);
        this.descuentoConIvaRadioButon.setEnabled(false);
    }//GEN-LAST:event_limpiarFacturaButonActionPerformed

    private void nombreCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.nombreCompradorTxt.getText().equals("Nombre")) {
            this.nombreCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_nombreCompradorTxtFocusGained

    private void limpiarTiendaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTiendaButonActionPerformed
        // TODO add your handling code here:
        this.seleccionarTiendaComboBox.setSelectedIndex(0);
        this.nombreTiendaTxt.setText("Nombre de la tienda");
        this.webTIendaTxt.setText("Página web");
        this.direccionTiendaTxt.setText("Dirección");
    }//GEN-LAST:event_limpiarTiendaButonActionPerformed

    private void nombreCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.nombreCompradorTxt.getText().isEmpty()) {
            this.nombreCompradorTxt.setText("Nombre");
        }
    }//GEN-LAST:event_nombreCompradorTxtFocusLost

    private void apellidosCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.apellidosCompradorTxt.getText().equals("Apellidos")) {
            this.apellidosCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_apellidosCompradorTxtFocusGained

    private void apellidosCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.apellidosCompradorTxt.getText().isEmpty()) {
            this.apellidosCompradorTxt.setText("Apellidos");
        }
    }//GEN-LAST:event_apellidosCompradorTxtFocusLost

    private void dniCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dniCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.dniCompradorTxt.getText().equals("DNI")) {
            this.dniCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_dniCompradorTxtFocusGained

    private void dniCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dniCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.dniCompradorTxt.getText().isEmpty()) {
            this.dniCompradorTxt.setText("DNI");
        }
    }//GEN-LAST:event_dniCompradorTxtFocusLost

    private void emailCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.emailCompradorTxt.getText().equals("Email")) {
            this.emailCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_emailCompradorTxtFocusGained

    private void emailCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.emailCompradorTxt.getText().isEmpty()) {
            this.emailCompradorTxt.setText("Email");
        }
    }//GEN-LAST:event_emailCompradorTxtFocusLost

    private void telefonoCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.telefonoCompradorTxt.getText().equals("Teléfono")) {
            this.telefonoCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_telefonoCompradorTxtFocusGained

    private void telefonoCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.telefonoCompradorTxt.getText().isEmpty()) {
            this.telefonoCompradorTxt.setText("Teléfono");
        }
    }//GEN-LAST:event_telefonoCompradorTxtFocusLost

    private void direccionCompradorTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionCompradorTxtFocusGained
        // TODO add your handling code here:
        if (this.direccionCompradorTxt.getText().equals("Dirección")) {
            this.direccionCompradorTxt.setText(null);
        }
    }//GEN-LAST:event_direccionCompradorTxtFocusGained

    private void direccionCompradorTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionCompradorTxtFocusLost
        // TODO add your handling code here:
        if (this.direccionCompradorTxt.getText().isEmpty()) {
            this.direccionCompradorTxt.setText("Dirección");
        }
    }//GEN-LAST:event_direccionCompradorTxtFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.compradorExistenteComboBox.setSelectedIndex(0);
        this.nombreCompradorTxt.setText("Nombre");
        this.apellidosCompradorTxt.setText("Apellidos");
        this.dniCompradorTxt.setText("DNI");
        this.emailCompradorTxt.setText("Email");
        this.telefonoCompradorTxt.setText("Teléfono");
        this.direccionCompradorTxt.setText("Dirección");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            boolean flag = false;
            boolean x = this.hayArticulosEnTabla();
            boolean y = this.datosFacturaCorrectos();
            boolean z = this.datosTiendaCorrectos();
            if (x && y && z) {
                Tienda t = new Tienda(this.nombreTiendaTxt.getText().toUpperCase(), this.webTIendaTxt.getText().toLowerCase(), this.direccionTiendaTxt.getText().toUpperCase());
                Comprador c = new Comprador(this.dniCompradorTxt.getText().toUpperCase(), this.nombreCompradorTxt.getText().toUpperCase(), this.apellidosCompradorTxt.getText().toUpperCase(), this.emailCompradorTxt.getText().toLowerCase(), this.direccionCompradorTxt.getText().toUpperCase(), this.telefonoCompradorTxt.getText());
                //Creamos el GregorianCalendar con la fecha de compra
                GregorianCalendar fecha = new GregorianCalendar(Integer.parseInt(this.añoFechaTxt.getText()), (Integer.parseInt(this.mesFechaTxt.getText()) - 1), Integer.parseInt(this.diaFechaTxt.getText()));
                //Deducimos la forma de pago:
                String formaPago = null;
                if (this.formaPagoComboBox.getSelectedIndex() != 9) {
                    formaPago = this.formaPagoComboBox.getSelectedItem().toString().toUpperCase();
                } else {
                    formaPago = this.otraFormaPagoTxt.getText().toUpperCase();
                }
                //Deducimos los gastos de envío SIN IVA:
                double gEnvioSinIVA;
                if (this.gastosEnvioConIvaRadioButon.isSelected()) {
                    //Incluyen el iva, hay que quitarlo:
                    gEnvioSinIVA = Double.parseDouble(this.gastosEnvioTxt.getText()) / 1.21;
                } else {
                    gEnvioSinIVA = Double.parseDouble(this.gastosEnvioTxt.getText());
                }
                //Deducimos cuanto es el descuento CON IVA:
                double descuentoConIVA = 0;
                if (this.contieneDescuentoRadioButon.isSelected()) {
                    if (this.descuentoConIvaRadioButon.isSelected()) {
                        descuentoConIVA = Double.parseDouble(this.descuentoTxt.getText());
                    } else {
                        descuentoConIVA = Double.parseDouble(this.descuentoTxt.getText()) + (Double.parseDouble(this.descuentoTxt.getText()) * 0.21);
                    }
                }
                //Ya tenemos todo lo necesario. Ahora, creamos la factura
                Factura f = new Factura(t, c, fecha, Integer.parseInt(this.numeroPedidoTxt.getText()), formaPago, this.listaProductos, gEnvioSinIVA, descuentoConIVA);
                //La factura está creada, hay que añadir la factura al programa para que la guarde.
                Control.añadirFactura(f);
                this.padre.escribirTabla(Control.facturas);
                flag = true;
                if (flag) {
                    JOptionPane.showMessageDialog(this, "Factura añadida con éxito", "Operación finalizada", JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (NumberFormatException | HeadlessException error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error en inserción de datos", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void resetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButonActionPerformed
        // TODO add your handling code here:
        CrearFactura n = new CrearFactura(this.padre);
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_resetButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CrearFactura(this.).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosCompradorTxt;
    private javax.swing.JTextField añoFechaTxt;
    private javax.swing.JTextField codigoArticuloTxt;
    private javax.swing.JComboBox<String> compradorExistenteComboBox;
    private javax.swing.JRadioButton contieneDescuentoRadioButon;
    private javax.swing.JRadioButton descuentoConIvaRadioButon;
    private javax.swing.JTextField descuentoTxt;
    private javax.swing.JTextField diaFechaTxt;
    private javax.swing.JTextField direccionCompradorTxt;
    private javax.swing.JTextField direccionTiendaTxt;
    private javax.swing.JTextField dniCompradorTxt;
    private javax.swing.JTextField emailCompradorTxt;
    private javax.swing.JComboBox<String> formaPagoComboBox;
    private javax.swing.JRadioButton gastosEnvioConIvaRadioButon;
    private javax.swing.JTextField gastosEnvioTxt;
    private javax.swing.JButton insertarArticuloButon;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiarArticuloButon;
    private javax.swing.JButton limpiarFacturaButon;
    private javax.swing.JButton limpiarTiendaButon;
    private javax.swing.JTextField mesFechaTxt;
    private javax.swing.JTextField nombreArticuloTxt;
    private javax.swing.JTextField nombreCompradorTxt;
    private javax.swing.JTextField nombreTiendaTxt;
    private javax.swing.JTextField numeroPedidoTxt;
    private javax.swing.JTextField otraFormaPagoTxt;
    private javax.swing.JRadioButton precioArticuloIncluyeIvaRadioButon;
    private javax.swing.JTextField precioArticuloTxt;
    private javax.swing.JButton resetButon;
    private javax.swing.JComboBox<String> seleccionarTiendaComboBox;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTextField telefonoCompradorTxt;
    private javax.swing.JTextField tipoArticuloTxt;
    private javax.swing.JTextField webTIendaTxt;
    // End of variables declaration//GEN-END:variables
}
